import { describe, expect, it } from "vitest";
import { FORMATIONS, type Formation } from "@/domain/enums";
import {
  buildInitialLineupDraft,
  canSubmitLineup,
  getEffectiveOverall,
  getFormationSlots,
  getLineupSourceNotice,
  hydrateLineupDraft,
  isImprovised,
  validateLineupDraft,
  type LineupDraft,
  type LineupRosterPlayer,
  type SavedLineupSnapshot,
} from "@/domain/lineup";

const roster: LineupRosterPlayer[] = [
  player("cp-gk", "GK", 70),
  player("cp-def-1", "DEF", 71),
  player("cp-def-2", "DEF", 72),
  player("cp-mid", "MID", 73),
  player("cp-ata", "ATA", 74),
  player("cp-reserve", "MID", 65),
];

function player(id: string, position: LineupRosterPlayer["position"], overall: number) {
  const attributes = {
    velocity: overall,
    finishing: overall,
    passing: overall,
    dribbling: overall,
    defending: overall,
    physical: overall,
    goalkeeping: overall,
  };
  return {
    clubPlayerId: id,
    name: id,
    position,
    overall,
    attributes,
    isReserved: false,
  } satisfies LineupRosterPlayer;
}

function validDraft(formation: Formation = "1-2-1-1"): LineupDraft {
  const draft = buildInitialLineupDraft(formation, "balanced");
  draft.starters = {
    "GK-1": "cp-gk",
    "DEF-1": "cp-def-1",
    "DEF-2": "cp-def-2",
    "MID-1": "cp-mid",
    "ATA-1": "cp-ata",
  };
  draft.reserves = ["cp-reserve"];
  return draft;
}

describe("lineup formation helpers", () => {
  it("accepts every supported formation from the shared enum list", () => {
    for (const formation of FORMATIONS) {
      expect(getFormationSlots(formation)).toHaveLength(5);
    }
  });

  it("requires the correct starter slots for a formation", () => {
    expect(getFormationSlots("1-1-2-1").map((slot) => slot.key)).toEqual([
      "GK-1",
      "DEF-1",
      "MID-1",
      "MID-2",
      "ATA-1",
    ]);
  });
});

describe("lineup validation", () => {
  it("requires five starters in the expected formation slots", () => {
    const draft = validDraft();
    delete draft.starters["ATA-1"];

    const result = validateLineupDraft(draft, roster);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain("Preencha a posição ATA 1.");
  });

  it("rejects duplicated players across starters and reserves", () => {
    const draft = validDraft();
    draft.reserves = ["cp-mid"];

    const result = validateLineupDraft(draft, roster);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain("O mesmo jogador não pode aparecer duas vezes.");
  });

  it("rejects unsupported styles before saving", () => {
    const draft = { ...validDraft(), style: "pressing" };

    const result = validateLineupDraft(draft, roster);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain("Estilo de jogo invalido.");
  });

  it("allows a complete valid lineup", () => {
    expect(validateLineupDraft(validDraft(), roster).valid).toBe(true);
  });
});

describe("lineup improvisation preview", () => {
  it("identifies improvised players and shows the effective overall", () => {
    const player = roster[1];

    expect(isImprovised(player, "MID")).toBe(true);
    expect(getEffectiveOverall(player, "MID")).toBe(60);
  });
});

describe("lineup persisted state", () => {
  it("loads saved starters and reserves into the draft", () => {
    const saved: SavedLineupSnapshot = {
      formation: "1-2-1-1",
      style: "defensive",
      isAutoGenerated: false,
      players: [
        { clubPlayerId: "cp-gk", slotPosition: "GK", slotIndex: 1, isStarter: true },
        { clubPlayerId: "cp-def-1", slotPosition: "DEF", slotIndex: 1, isStarter: true },
        { clubPlayerId: "cp-def-2", slotPosition: "DEF", slotIndex: 2, isStarter: true },
        { clubPlayerId: "cp-mid", slotPosition: "MID", slotIndex: 1, isStarter: true },
        { clubPlayerId: "cp-ata", slotPosition: "ATA", slotIndex: 1, isStarter: true },
        { clubPlayerId: "cp-reserve", slotPosition: "MID", slotIndex: 1, isStarter: false },
      ],
    };

    const draft = hydrateLineupDraft(saved);

    expect(draft.style).toBe("defensive");
    expect(draft.starters["DEF-2"]).toBe("cp-def-2");
    expect(draft.reserves).toEqual(["cp-reserve"]);
  });

  it("shows the automatic lineup warning when there is no manual lineup", () => {
    expect(getLineupSourceNotice(null)).toContain("escalação automática");
  });

  it("distinguishes automatic lineups exposed by the backend", () => {
    expect(
      getLineupSourceNotice({
        formation: "1-2-1-1",
        style: "balanced",
        isAutoGenerated: true,
        players: [],
      }),
    ).toContain("gerada automaticamente");
  });
});

describe("lineup submit state", () => {
  it("disables saving when the lineup is blocked by the deadline", () => {
    const state = canSubmitLineup({
      validation: validateLineupDraft(validDraft(), roster),
      isSaving: false,
      isBlocked: true,
    });

    expect(state.canSubmit).toBe(false);
    expect(state.reason).toBe("escalação bloqueada");
  });
});
