import { improvisationMultiplier } from "@/domain/calculators/multipliers";
import {
  FORMATIONS,
  PLAYER_ATTRIBUTE_KEYS,
  PLAY_STYLES,
  type Formation,
  type PlayerAttributeKey,
  type PlayerPosition,
  type PlayStyle,
} from "@/domain/enums";
import type { PlayerAttributes } from "@/domain/types";

export type LineupSlotKey = `${PlayerPosition}-${number}`;

export interface FormationSlot {
  key: LineupSlotKey;
  position: PlayerPosition;
  slotIndex: number;
  label: string;
}

export interface LineupRosterPlayer {
  clubPlayerId: string;
  name: string;
  position: PlayerPosition;
  overall: number;
  attributes: PlayerAttributes;
  isReserved: boolean;
  attributeProgress?: Array<{
    attribute: PlayerAttributeKey;
    progress: number;
    updatedAt: string;
  }>;
}

export interface LineupPlayerSelection {
  clubPlayerId: string;
  slotPosition: PlayerPosition;
  slotIndex: number;
  isStarter: boolean;
}

export interface LineupDraft {
  formation: Formation;
  style: PlayStyle | string;
  starters: Partial<Record<LineupSlotKey, string>>;
  reserves: string[];
}

export interface SavedLineupSnapshot {
  formation: Formation;
  style: PlayStyle;
  isAutoGenerated: boolean;
  players: LineupPlayerSelection[];
}

export interface LineupValidationResult {
  valid: boolean;
  errors: string[];
  players: LineupPlayerSelection[];
}

const FORMATION_SLOT_COUNTS = {
  "1-2-1-1": { GK: 1, DEF: 2, MID: 1, ATA: 1 },
  "1-1-2-1": { GK: 1, DEF: 1, MID: 2, ATA: 1 },
  "1-1-1-2": { GK: 1, DEF: 1, MID: 1, ATA: 2 },
  "0-2-2-1": { GK: 0, DEF: 2, MID: 2, ATA: 1 },
} satisfies Record<Formation, Record<PlayerPosition, number>>;

const SLOT_ORDER: PlayerPosition[] = ["GK", "DEF", "MID", "ATA"];

export function getFormationSlots(formation: Formation): FormationSlot[] {
  const counts = FORMATION_SLOT_COUNTS[formation];
  return SLOT_ORDER.flatMap((position) =>
    Array.from({ length: counts[position] }, (_, index) => {
      const slotIndex = index + 1;
      return {
        key: `${position}-${slotIndex}` as LineupSlotKey,
        position,
        slotIndex,
        label: `${position} ${slotIndex}`,
      };
    }),
  );
}

export function buildInitialLineupDraft(
  formation: Formation = FORMATIONS[0],
  style: PlayStyle = "balanced",
): LineupDraft {
  return { formation, style, starters: {}, reserves: [] };
}

export function hydrateLineupDraft(saved: SavedLineupSnapshot | null): LineupDraft {
  if (!saved) return buildInitialLineupDraft();

  const draft = buildInitialLineupDraft(saved.formation, saved.style);
  for (const player of saved.players) {
    if (player.isStarter) {
      draft.starters[slotKey(player.slotPosition, player.slotIndex)] = player.clubPlayerId;
    } else {
      draft.reserves.push(player.clubPlayerId);
    }
  }
  return draft;
}

export function validateLineupDraft(
  draft: LineupDraft,
  roster: readonly LineupRosterPlayer[],
): LineupValidationResult {
  const errors: string[] = [];
  const rosterIds = new Set(roster.map((player) => player.clubPlayerId));
  const players: LineupPlayerSelection[] = [];
  const seenIds = new Set<string>();
  const slots = getFormationSlots(draft.formation);

  if (!PLAY_STYLES.includes(draft.style as PlayStyle)) {
    errors.push("Estilo de jogo invalido.");
  }

  for (const slot of slots) {
    const clubPlayerId = draft.starters[slot.key];
    if (!clubPlayerId) {
      errors.push(`Preencha a posicao ${slot.label}.`);
      continue;
    }
    players.push({
      clubPlayerId,
      slotPosition: slot.position,
      slotIndex: slot.slotIndex,
      isStarter: true,
    });
  }

  draft.reserves.forEach((clubPlayerId, index) => {
    if (!clubPlayerId) return;
    players.push({
      clubPlayerId,
      slotPosition: "MID",
      slotIndex: index + 1,
      isStarter: false,
    });
  });

  for (const player of players) {
    if (seenIds.has(player.clubPlayerId)) {
      errors.push("O mesmo jogador nao pode aparecer duas vezes.");
      break;
    }
    seenIds.add(player.clubPlayerId);
  }

  if (players.some((player) => !rosterIds.has(player.clubPlayerId))) {
    errors.push("A escalacao contem jogador que nao pertence ao seu elenco.");
  }

  if (players.filter((player) => player.isStarter).length !== 5) {
    errors.push("A escalacao precisa ter 5 titulares.");
  }

  if (players.filter((player) => !player.isStarter).length > 5) {
    errors.push("A escalacao permite no maximo 5 reservas.");
  }

  return { valid: errors.length === 0, errors, players };
}

export function isImprovised(
  player: Pick<LineupRosterPlayer, "position">,
  slotPosition: PlayerPosition,
): boolean {
  return player.position !== slotPosition;
}

export function getImprovisationPenalty(
  player: Pick<LineupRosterPlayer, "position">,
  slotPosition: PlayerPosition,
): number {
  return 1 - improvisationMultiplier(player.position, slotPosition);
}

export function getEffectiveOverall(
  player: Pick<LineupRosterPlayer, "position" | "overall">,
  slotPosition: PlayerPosition,
): number {
  return Math.round(player.overall * improvisationMultiplier(player.position, slotPosition));
}

export function getLineupSourceNotice(saved: SavedLineupSnapshot | null): string {
  if (!saved) {
    return "Sem escalacao salva. Se voce nao salvar, a escalacao automatica do backend sera usada.";
  }
  if (saved.isAutoGenerated) {
    return "Esta escalacao foi gerada automaticamente pelo backend.";
  }
  return "Escalacao salva pelo usuario.";
}

export function canSubmitLineup({
  validation,
  isSaving,
  isBlocked,
}: {
  validation: LineupValidationResult;
  isSaving: boolean;
  isBlocked: boolean;
}): { canSubmit: boolean; reason: string | null } {
  if (isSaving) return { canSubmit: false, reason: "salvando" };
  if (isBlocked) return { canSubmit: false, reason: "escalação bloqueada" };
  if (!validation.valid) return { canSubmit: false, reason: "escalação inválida" };
  return { canSubmit: true, reason: null };
}

export function getAttributeEntries(player: Pick<LineupRosterPlayer, "attributes">) {
  return PLAYER_ATTRIBUTE_KEYS.map((key) => ({ key, value: player.attributes[key] }));
}

function slotKey(position: PlayerPosition, slotIndex: number): LineupSlotKey {
  return `${position}-${slotIndex}` as LineupSlotKey;
}
