/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedMercadoRouteImport } from './routes/_authenticated/mercado'
import { Route as AuthenticatedElencoRouteImport } from './routes/_authenticated/elenco'
import { Route as AuthenticatedCriarClubeRouteImport } from './routes/_authenticated/criar-clube'
import { Route as AuthenticatedClassificacaoRouteImport } from './routes/_authenticated/classificacao'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAbrirPacoteRouteImport } from './routes/_authenticated/abrir-pacote'
import { Route as ApiInternalJobsRetryRouteImport } from './routes/api/internal/jobs/retry'
import { Route as ApiInternalJobsProcessDueRoundsRouteImport } from './routes/api/internal/jobs/process-due-rounds'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMercadoRoute = AuthenticatedMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElencoRoute = AuthenticatedElencoRouteImport.update({
  id: '/elenco',
  path: '/elenco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarClubeRoute = AuthenticatedCriarClubeRouteImport.update({
  id: '/criar-clube',
  path: '/criar-clube',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassificacaoRoute =
  AuthenticatedClassificacaoRouteImport.update({
    id: '/classificacao',
    path: '/classificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbrirPacoteRoute =
  AuthenticatedAbrirPacoteRouteImport.update({
    id: '/abrir-pacote',
    path: '/abrir-pacote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiInternalJobsRetryRoute = ApiInternalJobsRetryRouteImport.update({
  id: '/api/internal/jobs/retry',
  path: '/api/internal/jobs/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalJobsProcessDueRoundsRoute =
  ApiInternalJobsProcessDueRoundsRouteImport.update({
    id: '/api/internal/jobs/process-due-rounds',
    path: '/api/internal/jobs/process-due-rounds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/abrir-pacote': typeof AuthenticatedAbrirPacoteRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/classificacao': typeof AuthenticatedClassificacaoRoute
  '/criar-clube': typeof AuthenticatedCriarClubeRoute
  '/elenco': typeof AuthenticatedElencoRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/api/internal/jobs/process-due-rounds': typeof ApiInternalJobsProcessDueRoundsRoute
  '/api/internal/jobs/retry': typeof ApiInternalJobsRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/abrir-pacote': typeof AuthenticatedAbrirPacoteRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/classificacao': typeof AuthenticatedClassificacaoRoute
  '/criar-clube': typeof AuthenticatedCriarClubeRoute
  '/elenco': typeof AuthenticatedElencoRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/api/internal/jobs/process-due-rounds': typeof ApiInternalJobsProcessDueRoundsRoute
  '/api/internal/jobs/retry': typeof ApiInternalJobsRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/abrir-pacote': typeof AuthenticatedAbrirPacoteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/classificacao': typeof AuthenticatedClassificacaoRoute
  '/_authenticated/criar-clube': typeof AuthenticatedCriarClubeRoute
  '/_authenticated/elenco': typeof AuthenticatedElencoRoute
  '/_authenticated/mercado': typeof AuthenticatedMercadoRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/api/internal/jobs/process-due-rounds': typeof ApiInternalJobsProcessDueRoundsRoute
  '/api/internal/jobs/retry': typeof ApiInternalJobsRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/abrir-pacote'
    | '/admin'
    | '/app'
    | '/classificacao'
    | '/criar-clube'
    | '/elenco'
    | '/mercado'
    | '/trocar-senha'
    | '/api/internal/jobs/process-due-rounds'
    | '/api/internal/jobs/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/abrir-pacote'
    | '/admin'
    | '/app'
    | '/classificacao'
    | '/criar-clube'
    | '/elenco'
    | '/mercado'
    | '/trocar-senha'
    | '/api/internal/jobs/process-due-rounds'
    | '/api/internal/jobs/retry'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/_authenticated/abrir-pacote'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/classificacao'
    | '/_authenticated/criar-clube'
    | '/_authenticated/elenco'
    | '/_authenticated/mercado'
    | '/_authenticated/trocar-senha'
    | '/api/internal/jobs/process-due-rounds'
    | '/api/internal/jobs/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ApiInternalJobsProcessDueRoundsRoute: typeof ApiInternalJobsProcessDueRoundsRoute
  ApiInternalJobsRetryRoute: typeof ApiInternalJobsRetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mercado': {
      id: '/_authenticated/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof AuthenticatedMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/elenco': {
      id: '/_authenticated/elenco'
      path: '/elenco'
      fullPath: '/elenco'
      preLoaderRoute: typeof AuthenticatedElencoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar-clube': {
      id: '/_authenticated/criar-clube'
      path: '/criar-clube'
      fullPath: '/criar-clube'
      preLoaderRoute: typeof AuthenticatedCriarClubeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classificacao': {
      id: '/_authenticated/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof AuthenticatedClassificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abrir-pacote': {
      id: '/_authenticated/abrir-pacote'
      path: '/abrir-pacote'
      fullPath: '/abrir-pacote'
      preLoaderRoute: typeof AuthenticatedAbrirPacoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/internal/jobs/retry': {
      id: '/api/internal/jobs/retry'
      path: '/api/internal/jobs/retry'
      fullPath: '/api/internal/jobs/retry'
      preLoaderRoute: typeof ApiInternalJobsRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/jobs/process-due-rounds': {
      id: '/api/internal/jobs/process-due-rounds'
      path: '/api/internal/jobs/process-due-rounds'
      fullPath: '/api/internal/jobs/process-due-rounds'
      preLoaderRoute: typeof ApiInternalJobsProcessDueRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbrirPacoteRoute: typeof AuthenticatedAbrirPacoteRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClassificacaoRoute: typeof AuthenticatedClassificacaoRoute
  AuthenticatedCriarClubeRoute: typeof AuthenticatedCriarClubeRoute
  AuthenticatedElencoRoute: typeof AuthenticatedElencoRoute
  AuthenticatedMercadoRoute: typeof AuthenticatedMercadoRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbrirPacoteRoute: AuthenticatedAbrirPacoteRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClassificacaoRoute: AuthenticatedClassificacaoRoute,
  AuthenticatedCriarClubeRoute: AuthenticatedCriarClubeRoute,
  AuthenticatedElencoRoute: AuthenticatedElencoRoute,
  AuthenticatedMercadoRoute: AuthenticatedMercadoRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ApiInternalJobsProcessDueRoundsRoute: ApiInternalJobsProcessDueRoundsRoute,
  ApiInternalJobsRetryRoute: ApiInternalJobsRetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
